server:
  # HTTPS 端口（默认443，若服务器443端口被占用可改其他，如8443）
  port: 443
  ssl:
    # 证书文件路径（resources 根目录直接写文件名）
    key-store: classpath:ssl.pfx
    # 证书类型（PFX 证书对应 PKCS12）
    key-store-type: PKCS12
    # 证书密码（从 keystore.txt 中复制）
    key-store-password: t3qx2pac
    # 证书别名（默认即可，若有自定义需修改）
    key-alias: sgpy.top

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.182.241:3306/sgpy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: pangque_618

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: yimiao.sgpy.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  level:
    root: info
    org.springframework: warn
  file:
    name: logs/log.log

wechat:
  app_id: "wx7d8ba10c1e15dacb"
  app_secret: "4e46c24042f68e3f35e69cef55054b55"